name: delivery_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1  

  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/image.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/facebook.svg
    - assets/images/google.svg
    - assets/images/sms.svg
    - assets/images/email.svg
    - assets/images/avatar.png
    - assets/images/banner.png
    - assets/images/terra.png
    - assets/images/McDonald.png
    - assets/images/KFC.png
    - assets/images/chillox.png
    - assets/images/yakoyo.png
    - assets/images/chicken.png
    - assets/images/shawarma.png
    - assets/images/pizza.png
    - assets/images/jollof rice.png
    - assets/images/drinks.png
    - assets/images/white rice.png
    - assets/images/spaghetti.png
    - assets/images/shawarmaa.png
    - assets/images/pizzaa.png
    - assets/images/hamburger.png
    - assets/images/vegetable.png
    - assets/images/seafoodokro.png
    - assets/images/chickenn.png
    - assets/images/pasta.png
    - assets/images/chickensalad.png
    - assets/images/moimoi.png
    - assets/images/spicynoodles.png
    - assets/images/beefsalad.png
    - assets/images/eggpizza.png
    - assets/images/peppersoup.png
    - assets/images/jollofrice.png
    - assets/images/mcdonaldd.png
    - assets/images/fooddetail.png

