// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV6SIp2HeP1WtiN5iQWbEVYvBfApEs-14',
    appId: '1:590373414259:web:3cd4da3a46c3f2a7951106',
    messagingSenderId: '590373414259',
    projectId: 'delivery-app-48820',
    authDomain: 'delivery-app-48820.firebaseapp.com',
    storageBucket: 'delivery-app-48820.firebasestorage.app',
    measurementId: 'G-PF99X93SE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-vKP8iUxqDj3cQHu7at22sfPr6hzyqXY',
    appId: '1:590373414259:android:96db99fa3722e881951106',
    messagingSenderId: '590373414259',
    projectId: 'delivery-app-48820',
    storageBucket: 'delivery-app-48820.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPnogjRvPdFuwJLA7BRgkexDLqXIRU_lA',
    appId: '1:590373414259:ios:2886ef8b038948c0951106',
    messagingSenderId: '590373414259',
    projectId: 'delivery-app-48820',
    storageBucket: 'delivery-app-48820.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPnogjRvPdFuwJLA7BRgkexDLqXIRU_lA',
    appId: '1:590373414259:ios:2886ef8b038948c0951106',
    messagingSenderId: '590373414259',
    projectId: 'delivery-app-48820',
    storageBucket: 'delivery-app-48820.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV6SIp2HeP1WtiN5iQWbEVYvBfApEs-14',
    appId: '1:590373414259:web:b4335818a83ed280951106',
    messagingSenderId: '590373414259',
    projectId: 'delivery-app-48820',
    authDomain: 'delivery-app-48820.firebaseapp.com',
    storageBucket: 'delivery-app-48820.firebasestorage.app',
    measurementId: 'G-JD2BVM46CM',
  );
}
